### ISSUE TITLE
Where can i find autoexec folder?

### ISSUE THREAD

**Issue by inDail** [dxgi/roblox-client-manager#1]
Hello guys! Im not pro in coding, so, can you help me? Where can i find autoexec folder?

![image](https://github.com/dxgi/roblox-client-manager/assets/130224909/b31f89a4-8fc0-4887-9f54-d974dbd7630a)

**Comment by cousimzab** [comment]
no idea

**Comment by dxgi** [comment]
The same location where the executable of your executor is.

Do you even have an executor?

**Comment by DaBloxBoom** [comment]
how do i even make an executor?

**Comment by DaBloxBoom** [comment]
can u make an tutorial

**Comment by inDail** [comment]
> The same location where the executable of your executor is.
> 
> Do you even have an executor?

Egh, nah. Where can i get one? Or how can i make one ¯\_(ツ)_/¯

**Comment by dxgi** [comment]
Buy Krampus or something lol
